### PR TITLE
Initial Azure Support

### PR DESCRIPTION
**Pull request by zdmc23**
FYI: I am not quite sure what the change to `ruleset.xml` means for your repo, and I also updated `.gitignore` to include the required `vendor/` libraries (but continued to exclude the dev-only dependencies).  Please let me know if anything else needs to change.  Thx!

### CODE REVIEW

**Comment by cairocoder01** [comment]
@zdmc23 Can you remove all of the vendor files? They should not be included in the repo. That is the point of Composer (just like NPM): to have a reference to needed packages without having to include 1700 external code files in your repo.

Any chance you could make use of the API method instead of including direct access to Azure? The inclusion of all of those vendor files is going to make the install size of the plugin quite big, and I'd like to avoid that. Especially if people are not actually using the Azure part, they have to install a large amount of files they don't even use. This is why I avoided the same thing for Google Cloud. If we have to include libraries for each cloud provider, this plugin will be ginormous (and could possibly hit server file upload limits).

**Comment by zdmc23** [comment]
@cairocoder01  I included the vendor files bc I wasn't sure how updates work if the vendor files change and they're not included in the repo.  WordPress doesn't run Composer for you, so how would you handle a situation where a version update includes new vendor files?

I'd like to keep the official SDK support for Azure and also add support for AWS, GCP, Digital Ocean, etc..., in a similar manner. I'm less concerned about plugin size, though I do understand that concern and the desire to not have a bunch of dependency files that you're not using.

What about this: We could make your mappings code into a Composer package, and then have distinct plugins for each Cloud Provider, and your API method/Webhook, and just leverage the D.T mappings as vendor files?  Each plugin would share the D.T mappings, and then have it's specific dependencies to limit the upload size?

**Comment by zdmc23** [comment]
I am not sure about WP plugin deployment best practices, but what about a GitHub Action that runs `composer install` and performs a release of a zip for the plugin (including the vendor files), and that is what gets auto-updated via WP-Admin?  Then there is no need to track vendor files in the repo (proper, like you're saying), and we still get to auto-update (available in WP 5.5) with any introduction of new vendor dependencies between versions.

**Comment by cairocoder01** [comment]
Ah, are you thinking about when you download the repository as a zip and want to directly install it as a plugin? That's not the best way to do it. We'll build a separate release package that has all of the needed vendor files, but we don't want them stored in our own repo. We'll do it in the CI/CD process as you suggested in your latest comment.

Another option could be finding a way to use hooks to this plugin in order to add the other export functionality via separate plugins that just add in the bits that are needed to send the data to the given destinations? That way, you install the individual providers that you actually need.

**Comment by zdmc23** [comment]
Yes, chatting with Corsac also, and I think that he's onboard with the CI/CD process of having "composer install" run with an automated release upon merging into `master` branch, and then have `development` branch for pre-release commits and testing

I like that hooks option also.  What's the benefit of a hook to a plugin vs. a Composer package/dependency?  Is it simplicity, or something more?  I think that GitHub will host packages now.

**Comment by cairocoder01** [comment]
@zdmc23 I've set up all of the needed hooks and created a separate repo for the Azure provider: https://github.com/cairocoder01/disciple-tools-data-reporting-provider-azure

I also have a general sample provider repo (linked to in the main readme of this repo) that can be used for future providers. Let me know if anything is missing that you would need.

**Pull request closed without merging**
